server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5428/auth-service
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 21000
        linger.ms: 1
        request.timeout.ms: 20000

  cloud:
    openfeign:
      client:
        config:
          CUSTOMER-SERVICE:
            url: http://localhost:8082
          default:
            loggerLevel: BASIC
          feign:
            loggerLevel: BASIC

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  file:
    path: classpath:/resources/logs/auth-service.log
