server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5428/auth-service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: BASIC
          feign:
            loggerLevel: BASIC
#    config:
#      enabled: false

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  #      instance-id: ${spring.application.name}:${random.uuid}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
