server:
  port: 8096
spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: optional:file:.env[.properties]

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      properties:
        spring.json.trusted.packages: "springcloudms.inventoryservice.events"
        spring.json.type.mapping: "springcloudms.inventoryservice.events.AddNewBookEvent:springcloudms.notificationservice.events.AddNewBookEvent"
        auto.create.topics.enable: true
      group-id: cloudmicroservices-consumer-group

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: http://localhost

  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always