server:
  port: 8096
spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: optional:file:.env[.properties]

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: demo-microservices-consumer-group
      properties:
        spring.json.trusted.packages: '*'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: http://localhost

  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka