server:
  port: 8765
#
#jwt:
#  secret:
#    key: SldUX0FVVEhfU0VSVklDRV9BQ0NFU1NfU0VDUkVUX0tFWQ==

spring:
  application:
    name: API-GATEWAY
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
##        - id: auth-service
##          uri: lb://auth-service
##          predicates:
##            - Path=/api/auth/**
##          filters:
##            - name: CircuitBreaker
##              args:
##                name: auth-service
##                fallbackUri: forward:/authFallback
#
#        - id: customer-service
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#              - Path=/customer/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: customer-service
#                fallbackUri: forward:/customersFallback
#
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: order-service
#                fallbackUri: forward:/orderFallback
#
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#        - id: inventory-service
#          uri: lb://inventory-service
#          predicates:
#            - Path=/inventory/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: http://localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info
#        include: '*'

#Hystrix Config
hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Product Service
#        id: product_service_swagger
        url: /product/v3/api-docs
      - name: Order Service
#        id: order_service_swagger
        url: /order/v3/api-docs
      - name: Inventory Service
#        id: inventory_service_swagger
        url: /inventory/v3/api-docs
      - name: Customer Service
#        id: customer_service_swagger
        url: /customer/v3/api-docs

