server:
  port: 8092

spring:
  application:
    name: CUSTOMER-SERVICE

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
          show-sql: true
          format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5429/customer-service
    username: postgres
    password: postgres

  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.yaml

  cloud:
    openfeign:
      client:
        config:
          AUTH-SERVICE:
            url: http://localhost:8081
  kafka:
    consumer:
      group-id: cloudmicroservices-consumer-group
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      isolation-level: READ_COMMITTED
      properties:
        spring.json.trusted.packages: "*"
        auto.create.topics.enable: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
#      instance-id: ${spring.application.name}:${random.uuid}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka