CREATE TABLE orders (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_number VARCHAR (255) DEFAULT NULL,
    sku_code VARCHAR (255),
    price DECIMAL (19, 2),
    quantity INTEGER,
    PRIMARY KEY (id)
    );