server:
  port: 8093


inventory-service:
  host: lb://INVENTORY-SERVICE

spring:
  application:
    name: ORDER-SERVICE

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/order-service
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        connection-timeout: 5000
        ok-http:
          read-timeout: 5000
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
          inventory-service:
            url: http://localhost:8765/api/inventory

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    fetch-registry: true
    register-with-eureka: true
    eureka-service-url-poll-interval-seconds: 15
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#inventory-service:
#  host: lb://INVENTORY-SERVICE
#  host: localhost:8092