server:
  port: 8093

spring:
  application:
    name: ORDER-SERVICE

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          highlight_sql: true
          format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/order-service
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

#Kafka Consumer Config
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      group-id: cloudmicroservices-consumer-group
      isolation-level: READ_COMMITTED
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "springcloudms.orderservice.events"
        spring.json.type.mapping: "{springcloudms.authservice.dto.order.OrderAccountCreateRequestEvent:springcloudms.orderservice.events.handler.OrderEventsHandler}"
        auto.create.topics.enable: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        connection-timeout: 5000
        ok-http:
          read-timeout: 5000
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
          inventory-service:
            url: http://localhost:8765/api/inventory
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    fetch-registry: true
    register-with-eureka: true
    eureka-service-url-poll-interval-seconds: 15
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui