server:
  port: 8094

spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: http://localhost

  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka

    eureka-service-url-poll-interval-seconds: 15
    healthcheck:
      enabled: true