version: '4'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-inventory-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory-service
    ports:
      - "5431:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./docker/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql