version: '4'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-inventory-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory-service
    ports:
      - "5431:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./docker/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
#  kafka:
#    image: confluentinc/cp-kafka
#    container_name: kafka-inventory-service
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_KRAFT_BROKER_ID: 1
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://inventory-service:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 3